Backendless/Android-SDK

- src/com/backendless/Messaging.java
- src/com/backendless/exceptions/ExceptionMessage.java
http://bugs.backendless.com/browse/BKNDLSS-8533
> Added check for push notification recipient.

- src/com/backendless/Files.java
- src/com/backendless/files/security/AbstractFilePermission.java
> BKNDLSS-8769, BKNDLSS-8770

- src/com/backendless/Geo.java
- src/com/backendless/geo/geofence/GeoFenceMonitoring.java
http://bugs.backendless.com/browse/BKNDLSS-9614
> Removed billing restriction for fencing.

- src/com/backendless/Media.java
> fix for devided logic for play and publish

- src/com/backendless/servercode/extension/PersistenceExtender.java
Server sends error argument type mismatch when run search in data
> BKNDLSS-9988

- src/com/backendless/Messaging.java
- src/com/backendless/exceptions/ExceptionMessage.java
http://bugs.backendless.com/browse/BKNDLSS-10040
> Bkndlss 10040

- src/com/backendless/UserService.java
http://bugs.backendless.com/browse/BKNDLSS-11716
> [BKNDLSS-11716]: Fixed multiple login with stayLoggedIn option

- src/com/backendless/FootprintsManager.java
- src/com/backendless/Persistence.java
http://bugs.backendless.com/browse/BKNDLSS-11915
> fixed bugs in footprints logic

- src/com/backendless/SocialAsyncCallback.java
> BKNDLSS-12105 removed insecure method `onReceivedSslError`

- samples/UserService/FacebookSDKSamples/login/src/com/backendless/facebooklogin/Defaults.java
As a response to support question:
http://support.backendless.com/topic/android-login-and-authenticate-facebook-user-into-a-backendless-application#comment-14670
> Fixed url in a sample

- src/com/backendless/logging/LogBuffer.java
> BKNDLSS-12878 fixed order in log service

- src/com/backendless/BackendlessUser.java
… since extending it may lead to unexpected behaviour during data operations.
> Made BackendlessUser final

- src/com/backendless/Geo.java
http://bugs.backendless.com/browse/BKNDLSS-13871
> T 13871 list of geo categories casting fix

- src/com/backendless/DataStoreFactory.java
- src/com/backendless/IDataStore.java
- src/com/backendless/persistence/MapDrivenDataStore.java
Server-side has been refactored to return Integer for these calls.
This is a client-side fix to keep common behavior for REST and Android SDK.
> Relation management signatures change

- src/com/backendless/DataStoreFactory.java
- src/com/backendless/IDataStore.java
- src/com/backendless/Persistence.java
- src/com/backendless/persistence/MapDrivenDataStore.java
http://bugs.backendless.com/browse/BKNDLSS-13910
> T 13909 find by id with query builder

- src/com/backendless/AbstractDataPermission.java
- src/com/backendless/Persistence.java
Added correct assignment for tableName and objectId in AbstractDataPermission if dataObject is a Map.
> Ticket BKNDLSS 13993

- src/com/backendless/Logging.java
- src/com/backendless/logging/LogBuffer.java
http://bugs.backendless.com/browse/BKNDLSS-14620
Logger in BL creates a new thread when it should not
> BKNDLSS-14620

- src/com/backendless/Persistence.java
- src/com/backendless/persistence/MapDrivenDataStore.java
This allows to use SDK for Android API <19
> [BKNDLSS-16132]: Remove references to java.util.Objects class

- src/com/backendless/rt/AsynRTClient.java
- src/com/backendless/rt/MethodTypes.java
- src/com/backendless/rt/RTClient.java
- src/com/backendless/rt/RTClientFactory.java
- src/com/backendless/rt/RTClientSocketIO.java
- src/com/backendless/rt/RTMethodRequest.java
- src/com/backendless/rt/RTSubscription.java
- src/com/backendless/rt/SubscriptionNames.java
socket io implementation;
async decorator for client;
added client factory
> added RTClient;

- src/com/backendless/push/BackendlessPushService.java
- src/com/backendless/push/PushTemplateHelper.java
Code refactoring.
Added alpha channel for colors.
Fixed time from seconds to milliseconds.
Fix recreation for notification channels.
> Code refactoring.

- src/com/backendless/AndroidBackendlessPrefs.java
- src/com/backendless/Backendless.java
- src/com/backendless/BackendlessPrefs.java
- src/com/backendless/geo/LocationTracker.java
- src/com/backendless/push/BackendlessBroadcastReceiver.java
- src/com/backendless/push/BackendlessPushService.java
Migration to JobIntentService due to limitations in new Android 8 with backward compatibility to older versions.
> Migration to JobIntentService due to limitations in new Android 8

- build.gradle
- src/com/backendless/Backendless.java
- src/com/backendless/push/BackendlessBroadcastReceiver.java
- src/com/backendless/push/BackendlessPushService.java
- fix setUrl
- backward compatibility with plan push notification
> fix setUrl

- src/com/backendless/Backendless.java
Local CodeRunner fails to deploy.
> BKNDLSS-16797

- src/com/backendless/DataStoreFactory.java
- src/com/backendless/IDataStore.java
- src/com/backendless/Persistence.java
- src/com/backendless/exceptions/ExceptionMessage.java
- src/com/backendless/persistence/MapDrivenDataStore.java
added bulk create API BKNDLSS-15821
> bulk create API

- build.gradle
- src/com/backendless/push/BackendlessPushService.java
- src/com/backendless/push/PushTemplateHelper.java
Smart text added to headers (title and subtext) is rendered as a string instead of an actual value
> BKNDLSS-16742

- src/com/backendless/push/PushTemplateHelper.java
Added ability to send notification without any configuration.
> BKNDLSS-17258 NPE when sending empty template with message only

- src/com/backendless/push/BackendlessPushService.java
- src/com/backendless/push/PushTemplateHelper.java
BKNDLSS-17315 Immediate notifications sent via template editor should not get to a separate channel 
BKNDLSS-17324 PushWithTemplate method should publish Scheduled notifications if requested
> BKNDLSS-17315 / BKNDLSS-17324 Immediate and Schedule push

- README.md
- gradle.properties
- samples/DataService/tododemo/src/com/backendless/examples/dataservice/tododemo/Defaults.java
- samples/DataService/tododemo/src/com/backendless/examples/dataservice/tododemo/Main.java
- samples/EndlessMatchMaker/src/com/backendless/examples/endless/matchmaker/controllers/CreateTablesActivity.java
- samples/EndlessMatchMaker/src/com/backendless/examples/endless/matchmaker/controllers/LoginActivity.java
- samples/EndlessMatchMaker/src/com/backendless/examples/endless/matchmaker/utils/Defaults.java
- samples/EndlessTagging/src/com/backendless/examples/endless/tagging/Default.java
- samples/FenceDemo/src/com/backendless/fencedemo/Defaults.java
- samples/FenceDemo/src/com/backendless/fencedemo/FenceDemo.java
- samples/FileService/filedemo/app/src/main/java/com/backendless/examples/fileservice/filedemo/Defaults.java
- samples/FileService/filedemo/app/src/main/java/com/backendless/examples/fileservice/filedemo/MainActivity.java
- samples/GeoService/geodemo/src/com/backendless/examples/geoservice/geodemo/Defaults.java
- samples/GeoService/geodemo/src/com/backendless/examples/geoservice/geodemo/MainActivity.java
- samples/MessagingService/pubsubdemo/src/com/backendless/examples/messagingservice/pubsubdemo/ChatActivity.java
- samples/MessagingService/pubsubdemo/src/com/backendless/examples/messagingservice/pubsubdemo/Defaults.java
- samples/MessagingService/pubsubdemo/src/com/backendless/examples/messagingservice/pubsubdemo/MainActivity.java
- samples/MessagingService/pushdemo/src/com/backendless/examples/messagingservice/pushdemo/Defaults.java
- samples/UserService/rolesdemo/src/com/backendless/examples/userservice/rolesdemo/Defaults.java
- samples/UserService/rolesdemo/src/com/backendless/examples/userservice/rolesdemo/ui/LoginActivity.java
- samples/UserService/userservicedemo/src/com/backendless/examples/userservice/demo/MainActivity.java
- src/com/backendless/AndroidBackendlessPrefs.java
- src/com/backendless/AndroidHeadersManager.java
- src/com/backendless/AuthKeys.java
- src/com/backendless/Backendless.java
- src/com/backendless/BackendlessPrefs.java
- src/com/backendless/Files.java
- src/com/backendless/Invoker.java
- src/com/backendless/exceptions/ExceptionMessage.java
- src/com/backendless/rt/SocketIOConnectionManager.java
In every public API method in the code the "secretKey" argument renamed to "apiKey".
> [BKNDLSS-17927]: Change "secretKey" argument name to "apiKey"

- build.gradle
- src/com/backendless/AndroidBackendlessPrefs.java
> BKNDLSS-18065 setUrl in Android SDK causes exception in initializer

- src/com/backendless/Persistence.java
fixed: java.lang.ClassCastException: [Ljava.util.HashMap; cannot be cast to java.util.List
> BKNDLSS-18205 [DC] Call stored procedures does not work for MSSQL

- src/com/backendless/Persistence.java
Enable access to Users table via Map DataStore.
Remove verification from method:
```java
IDataStore<Map> Backendless.Data.of( String tableName )
```
> Remove user table verification

- src/com/backendless/UserService.java
- src/com/backendless/UserServiceAndroidExtra.java
Added methods
```java
public void loginWithTwitterSdk( String authToken, String authTokenSecret, AsyncCallback<BackendlessUser> responder )
public void loginWithTwitterSdk( String authToken, String authTokenSecret, AsyncCallback<BackendlessUser> responder,
boolean stayLoggedIn )
public void loginWithTwitterSdk( String authToken, String authTokenSecret, Map<String, String> fieldsMappings,
AsyncCallback<BackendlessUser> responder )
public void loginWithTwitterSdk( String authToken, String authTokenSecret, Map<String, String> fieldsMappings,
AsyncCallback<BackendlessUser> responder, boolean stayLoggedIn )
```
> [BKNDLSS-16151] add loginWithTwitterSdk method

- src/com/backendless/Persistence.java
Bulk create API in Android environment ignores boolean values. SerialVersionUID values are passed to the server automatically in Android environment when using bulkCreate API
> BKNDLSS-19016. Fix createBulk for Android

- src/com/backendless/push/BackendlessFCMService.java
Fix push templates receiving. 
Change the Intent constructor to the one used before.
> [BKNDLSS-19408] Can't receive push notifications sent from `PushTemplates`

- src/com/backendless/Persistence.java
Create separated method to serialize entity before create/createBulk
> [BKNDLSS-19016] Create separated method to serialize entity 

- src/com/backendless/AndroidHeadersManager.java
- src/com/backendless/BLHeadersManager.java
- src/com/backendless/IHeadersManager.java
Required for Flutter SDK functionality.
> [BKNDLSS-19591]  Implement removeHeader() for String key

- src/com/backendless/atomic/AtomicCallback.java
Avoid NPE during API call with wrong App ID.
> [BKNDLSS-18367] Change error message if wrong appId

- src/com/backendless/transaction/OperationCreateBulkFactory.java
- src/com/backendless/transaction/OperationCreateBulkReturned.java
- src/com/backendless/transaction/OperationCreateFactory.java
- src/com/backendless/transaction/OperationCreateReturned.java
- src/com/backendless/transaction/OperationUpdateFactory.java
- src/com/backendless/transaction/OperationUpdateReturned.java
> [BKNDLSS-22010]: Transaction create from instance fail - throw exception

- src/com/backendless/UserService.java
Add the method to login user by its objectId.
> [BKNDLSS-20551] Add login by id

- src/com/backendless/persistence/JSONUpdateBuilder.java
Update the "___operation" field values.
> [BKNDLSS-22834] Fix JSONUpdateBuilder operations

- src/com/backendless/UserService.java
Reverts "[BKNDLSS-23062] Java SDK. Methods for enabling/disabling users"
> Revert "[BKNDLSS-23062] Java SDK. Methods for enabling/disabling users"

- src/com/backendless/UserService.java
[BKNDLSS-23062] Java SDK. Methods for enabling/disabling users
> [BKNDLSS-23062] Java SDK. Methods for enabling/disabling users
